// should be sychronized with:
// https://git.onedata.org/projects/VFS/repos/ctool/browse/src/errors.erl

export default {
  // General errors
  badMessage: 'Internal error: client message could not be understood by the server.',
  noConnectionToOnezone: 'No connection to Onezone service.',
  noConnectionToPeerOneprovider: 'Proxy error: no connection to peer Oneprovider.',
  noConnectionToClusterNode: 'No connection to cluster node.',
  unregisteredOneprovider: 'This Oneprovider is not registered.',
  internalServerError: 'The server has encountered an error while processing this request.{{reference}}',
  notImplemented: 'This operation is not implemented.',
  notSupported: 'This operation is not supported.',
  serviceUnavailable: 'Service required for this operation is offline.',
  timeout: 'Operation timed out – please try again later.',
  temporaryFailure: 'The server reported a temporary failure – please try again later.',
  externalServiceOperationFailed: 'Your request could not be fulfilled due to problems with the external service "{{serviceName}}". This might be a temporary problem or a misconfiguration. Please try again later or contact the site administrators if the problem persists.',
  unauthorized: 'You must authenticate yourself to perform this operation.',
  forbidden: 'You are not authorized to perform this operation (insufficient privileges?).',
  notFound: 'The resource could not be found.',
  alreadyExists: 'The resource already exists.',
  fileAccess: 'Cannot access file {{path}}: {{errno}}',
  limitReached: 'The limit for {{resourceDescription}} has been reached: {{limit}}.',

  // POSIX errors
  posix: '{{errno}}',

  // Auth errors
  userBlocked: 'This user account has been blocked by the administrator and cannot be used unless it is unblocked again.',
  badBasicCredentials: 'Invalid username or password.',
  badIdpAccessToken: 'Provided access token for {{idp}} is not valid.',
  badToken: 'Provided token could not be understood by the server.',
  badServiceToken: 'Provided service token is not valid – {{tokenError}}',
  badConsumerToken: 'Provided consumer token is not valid – {{tokenError}}',
  tokenInvalid: 'Provided token is not valid.',
  tokenRevoked: 'Provided token has been revoked.',
  tokenTooLarge: 'Provided token exceeds the allowed size of {{limit}} bytes.',
  notAnAccessToken: 'Expected an identity token, but received a(n) {{received}}.',
  notAnIdentityToken: 'Expected an access token, but received a(n) {{received}}.',
  notAnInviteToken: 'Expected a(n) {{expectedInviteType}} invitation token, but received a(n) {{received}}.',
  tokenCaveatUnknown: 'Unknown caveat – {{caveat}}.',
  tokenCaveatUnverified: '{{caveatDescription}}',
  tokenTimeCaveatRequired: 'You must specify a time caveat with maximum TTL of {{maxTtl}} seconds.',
  tokenSubjectInvalid: 'The token subject is invalid (does not exist or is different than expected).',
  tokenServiceForbidden: 'The service ({{service}}) is forbidden for this subject.',
  inviteTokenSubjectNotAuthorized: 'The subject (creator) of this token is not (or not longer) authorized to issue such invitations.',
  inviteTokenUsageLimitReached: 'The usage limit of this invite token has been reached.',
  inviteTokenConsumerInvalid: 'The consumer ({{consumer}}) is invalid for this type of invite token.',
  inviteTokenTargetIdInvalid: 'The target id ({{id}}) is invalid for this type of invite token.',
  tokenSessionInvalid: 'This token was issued for a session that no longer exists.',

  // Graph Sync errors
  expectedHandshakeMessage: 'Connection to the server was lost or not fully established (expected handshake message).',
  handshakeAlreadyDone: 'Tried to initialize connection to the server, but it was already established (handshake already done).',
  badVersion: 'Could not negotiate protocol version. Versions supported by the server: {{supportedVersions}}.',
  badGRI: 'Provided GRI (Graph Resource Identifier) is invalid.',
  rpcUndefined: 'Requested RPC operation is not defined.',
  notSubscribable: 'Malformed request (not subscribable).',

  // Data validation errors
  malformedData: 'Malformed request (malformed data).',
  missingRequiredValue: 'Required value of "{{key}}" is missing.',
  missingAtLeastOneValue: 'Missing data, you must provide at least one of: {{keys}}.',
  badData: 'Value of "{{key}}" provided in request is invalid{{endingWithHint}}',
  badValueEmpty: 'Value of "{{key}}" provided in request cannot be empty.',
  badValueBoolean: 'Value of "{{key}}" provided in request must be a boolean.',
  badValueString: 'Value of "{{key}}" provided in request must be a string.',
  badValueStringTooLarge: 'Value of "{{key}}" provided in request cannot be larger than {{limit}} characters.',
  badValueListOfStrings: 'Value of "{{key}}" provided in request must be a list of strings.',
  badValueInteger: 'Value of "{{key}}" provided in request must be an integer.',
  badValueFloat: 'Value of "{{key}}" provided in request must be a float.',
  badValueJSON: 'Value of "{{key}}" provided in request must be a JSON.',
  badValueToken: 'Value of "{{key}}" provided in request is not valid token – {{tokenError}}',
  badValueTokenType: 'Value of "{{key}}" provided in request must be a valid token type.',
  badValueInviteType: 'Value of "{{key}}" provided in request must be a valid invite type.',
  badValueIPv4Address: 'Value of "{{key}}" provided in request must be a valid IPv4 address.',
  badValueListOfIPv4Addresses: 'Value of "{{key}}" provided in request must be a list of valid IPv4 adresses.',
  badValueTooLow: 'Value of "{{key}}" provided in request must be greater or equal to {{limit}}.',
  badValueTooHigh: 'Value of "{{key}}" provided in request should be less or equal to {{limit}}.',
  badValueNotInRange: 'Value of "{{key}}" provided in request should be between {{low}} and {{high}}.',
  badValueNotAllowed: 'Value of "{{key}}" provided in request is not allowed, valid values: {{allowed}}.',
  badValueListNotAllowed: 'Value of "{{key}}" provided in request must be a list, allowed values: {{allowed}}.',
  badValueIdNotFound: 'Resource specified in "{{key}}" does not exist.',
  badValueAmbiguousId: 'The Id (key: {{key}}) is ambiguous.',
  badValueIdentifier: 'Value of "{{key}}" provided in request must be a valid identifier.',
  badValueIdentifierOccupied: 'The identifier provided for "{{key}}" is occupied.',
  badValueOctal: 'Value of "{{key}}" provided in request is not a valid octal number.',
  badValueFilePath: 'Value provided in request must be a valid file path.',
  badValueFullName: 'Value provided in request must be a valid full name. More details below.',
  badValueUsername: 'Value provided in request must be a valid username. More details below.',
  badValuePassword: 'Value provided in request must be a valid password. More details below.',
  badValueEmail: 'Value provided in request must be a valid e-mail address.',
  badValueName: 'Value provided in request must be a valid name.',
  badValueDomain: 'Value provided in request must be a valid domain name.',
  badValueSubdomain: 'Value provided in request must be a valid subdomain name.',
  badValueCaveat: 'Provided caveats are invalid.',
  badValueQoSParameters: 'Provided QoS parameters are invalid.',
  timeSeriesCollectionMissingLayout: 'The request refers to a layout that is not reflected in the time series collection.',
  timeSeriesCollectionTooManyMetrics: 'The time series collection cannot have more than {{limit}} metrics.',
  badValueTimeSeriesCollectionConflictingMetricConfig: 'Provided metric config for time series {{timeSeriesName}} and metric {{metricName}} conflicts with existing metric config (see details).',
  badGuiPackage: 'Provider GUI package could not be understood by the server.',
  guiPackageTooLarge: 'Provider GUI package is too large.',
  guiPackageUnverified: 'GUI plugin package verification failed, because SHA checksum of uploaded package is not whitelisted. To allow uploading this package please contact Onezone administrator and ask to add harvester GUI checksum {{shaSum}} to /etc/oz_worker/compatibility.json configuration file.',
  invalidQosExpression: 'Invalid QoS expression.',
  illegalSupportStageTransition: 'Illegal support stage transition: this operation cannot be performed while the storage is in stage "{{currentStorageStage}}" and provider is in stage "{{currentProviderStage}}".',

  // State errors
  basicAuthNotSupported: 'Username & password sign-in is not supported by this Onezone.',
  basicAuthDisabled: 'Username & password sign-in is disabled for this user.',
  subdomainDelegationNotSupported: 'Subdomain delegation is not supported by this Onezone.',
  subdomainDelegationDisabled: 'This operation is not available as subdomain delegation is disabled for this Oneprovider.',
  spaceMarketplaceDisabled: 'Space marketplace is disabled for this Onezone.',
  protectedGroup: 'This group is protected and cannot be deleted',
  atmLambdaInUse: 'This lambda cannot be removed because it is used by the workflow schemas with following ids: {{atmWorkflowSchemas}}.',
  cannotRemoveLastOwner: 'Cannot remove the last owner – another owner must be assigned first. Ownership can be granted to any direct or effective member.',
  cannotDeleteEntity: 'Unexpected error while deleting the {{entityType}} (ID: "{{entityId}}").',
  cannotAddRelationToSelf: 'Cannot join group to itself.',
  relationDoesNotExist: 'The {{childType}} (ID: "{{childId}}") does not belong to the {{parentType}} (ID: {{parentId}}).',
  relationAlreadyExists: 'The {{childType}} (ID: "{{childId}}") already belongs to the {{parentType}} (ID: {{parentId}}).',
  spaceAlreadySupportedWithImportedStorage: 'Space (ID: "{{spaceId}}") is already supported with an imported storage (ID: "{{storageId}}").',

  // Op-worker errors
  userNotSupported: 'Authenticated user is not supported by this Oneprovider.',
  autoCleaningDisabled: 'Auto-cleaning is disabled.',
  filePopularityDisabled: 'File popularity is disabled.',
  spaceNotSupportedBy: 'Space (ID: {{spaceId}}) is not supported by the Oneprovider (ID: {{providerId}}).',
  notALocalStorageSupportingSpace: 'Storage (ID: {{storageId}}) does not belong to this Oneprovider (ID: {{providerId}}) and/or does not support the space (ID: {{spaceId}}).',
  storageInUse: 'Specified storage supports a space.',
  requiresAutoStorageImportMode: 'Operation requires space with auto storage import mode.',
  storageTestFailed: 'Failed to {{operation}} test file on storage.',
  requiresNonImportedStorage: 'Cannot apply for storage (ID: {{storageId}}) – this operation requires a non-imported storage.',
  requiresImportedStorage: 'Cannot apply for storage (ID: {{storageId}}) – this operation requires a non-imported storage.',
  requiresReadonlyStorage: 'Cannot apply for storage {{storageIdOrType}} – this operation requires a readonly storage.',
  requiresPosixCompatibleStorage: 'Cannot apply for storage (ID: {{storageId}}) – this operation requires a POSIX-compatible storage (any of: {{posixCompatibleStorages}}).',
  autoStorageImportNotSupported: 'Cannot configure auto storage import on storage (ID: {{storageId}}) – this operation requires any of: {{supportedStorages}} storage with canonical path type and on object storages (any of: {{supportedObjectStorages}}) it requires blockSize = 0.',
  storageImportNotSupported: 'Cannot configure storage import on storage (ID: {{storageId}}) – this operation requires storage with canonical path type and on object storages (any of: {{objectStorages}}) it requires blockSize = 0.',
  statOperationNotSupported: 'Storage (ID: {{storageId}}) does not support the `stat` operation or equivalent used for acquiring files metadata.',
  transferAlreadyEnded: 'The transfer has already ended.',
  transferNotEnded: 'The transfer has not ended yet.',
  viewNotExistsOn: 'The database view does not exist on the Oneprovider (ID: {{providerId}}).',
  viewQueryFailed: 'Query on view failed. Error category: {{category}}. Description: {{description}}.',
  quotaExceeded: 'Space\'s storage quota has been exceeded.',
  atmUnsupportedDataType: 'Bad automation data type: provided {{type}} is not one of: {{allowed}}.',
  atmDataTypeUnverified: 'Value provided in automation is not of expected type. More details below.',
  atmDataValueConstraintUnverified: 'Value provided in automation doesn\'t meet the constraints. More details below.',
  atmStoreCreationFailed: 'Failed to create automation store (ID: "{{atmStoreSchemaId}}") – {{specificError}}',
  atmStoreMissingRequiredInitialContent: 'Missing initial content required to create automation store.',
  atmStoreFrozen: 'Failed to perform operation on automation store (ID: "{{atmStoreSchemaId}}") as any modification is forbidden.',
  atmStoreTypeDisallowed: 'Bad automation store: the type of store (ID: "{{atmStoreSchemaId}}") must be one of: {{allowed}}.',
  atmStoreContentNotSet: 'Bad automation store: store (ID: "{{atmStoreSchemaId}}") must not be empty.',
  atmStoreNotFound: 'Bad automation store: store (ID: "{{atmStoreSchemaId}}") does not exist.',
  atmWorkflowEmpty: 'Bad automation workflow: no lanes defined.',
  atmWorkflowExecutionStopping: 'Specified automation workflow execution is already stopping.',
  atmWorkflowExecutionStopped: 'Specified automation workflow execution has already stopped.',
  atmWorkflowExecutionNotStopped: 'Specified automation workflow execution has not stopped yet.',
  atmWorkflowExecutionEnded: 'Specified automation workflow execution has already ended.',
  atmWorkflowExecutionNotEnded: 'Specified automation workflow execution has not ended yet.',
  atmWorkflowExecutionNotResumable: 'Specified automation workflow execution cannot be resumed.',
  atmLaneEmpty: 'Bad automation lane: lane (ID: "{{atmLaneSchemaId}}") must not be empty.',
  atmLaneExecutionCreationFailed: 'Failed to create automation lane execution (ID: "{{atmLaneSchemaId}}") – {{specificError}}',
  atmLaneExecutionInitiationFailed: 'Failed to initiate automation lane execution (ID: "{{atmLaneSchemaId}}") – {{specificError}}',
  atmLaneExecutionRetryFailed: 'Failed to retry specified lane execution. Lane execution can be retried only if all items have been processed but some of them failed.',
  atmLaneExecutionRerunFailed: 'Failed to rerun specified lane execution. Lane execution can be rerun only if it is in one of the following states: "finished", "failed", "cancelled".',
  atmParallelBoxEmpty: 'Bad automation parallel box: parallel box (ID: "{{atmParallelBoxSchemaId}}") must not be empty.',
  atmParallelBoxExecutionCreationFailed: 'Failed to create automation parallel box execution (ID: "{{atmParallelBoxSchemaId}}") – {{specificError}}',
  atmParallelBoxExecutionInitiationFailed: 'Failed to initiate automation parallel box execution (ID: "{{atmParallelBoxSchemaId}}") – {{specificError}}',
  atmTaskExecutionCreationFailed: 'Failed to create automation task execution (ID: "{{atmTaskSchemaId}}") – {{specificError}}',
  atmTaskExecutionInitiationFailed: 'Failed to initiate automation task execution (ID: "{{atmTaskSchemaId}}") – {{specificError}}',
  atmLambdaConfigBadValue: 'Bad value provided for parameter "{{parameterName}}" of lambda config (see details).',
  atmTaskArgMapperForRequiredLambdaArgMissing: 'Missing argument mapper for required lambda argument "{{argument}}".',
  atmTaskArgMapperForNonexistentLambdaArg: 'Found excessive argument mapper for nonexistent lambda argument "{{argument}}".',
  atmTaskArgMappingFailed: 'Failed to map automation task execution argument "{{argument}}" – {{specificError}}',
  atmTaskArgMapperUnsupportedValueBuilder: 'Bad automation task argument value builder: type "{{type}}" not supported – must be one of: {{supported}}.',
  atmTaskArgMapperIteratedItemQueryFailed: 'Failed to perform query on iterated item. More details below.',
  atmTaskResultMissing: 'Missing required value for result "{{result}}".',
  atmTaskResultMappingFailed: 'Failed to map automation task execution result "{{result}}" – {{specificError}}',
  atmTaskResultDispatchFailed: '"Failed to dispatch automation task execution result to automation store (ID: {{"atmStoreSchemaId"}}) – {{specificError}}',
  atmTaskExecutionEnded: 'Specified automation task execution has already ended.',
  atmJobBatchWithdrawn: 'Previosuly scheduled job batch has been withdrawn.',
  atmJobBatchCrashed: 'Job batch execution has crashed.',
  atmOpenfaasNotConfigured: 'OpenFaaS service is not configured.',
  atmOpenfaasUnreachable: 'Cannot connect to OpenFaaS service.',
  atmOpenfaasUnhealthy: 'OpenFaaS service is unhealthy.',
  atmOpenfaasQueryFailed: 'Failed to query OpenFaaS service. More details below.',
  atmOpenfaasFunctionRegistrationFailed: 'Failed to register function in OpenFaaS service.',
  atmInvalidStatusTransition: 'Invalid status transition. More details below.',
  dirStatsDisabledForSpace: 'Directory statistics collection is disabled for this space.',
  dirStatsNotReady: 'Requested directory statistics are not ready yet — calculation is in progress.',
  forbiddenForCurrentArchiveState: 'This operation is forbidden while the archive state is {{currentState}}.',
  nestedArchiveDeletionForbidden: 'This archive cannot be deleted since it is nested in another archive.',
  recallTargetConflict: 'Conflict — recall target cannot be within a directory that is being recalled.',

  // Onepanel errors
  errorOnNodes: 'Error on nodes {{hostnames}}: {{error}}',
  dnsServersUnreachable: 'Error fetching DNS records. Used servers: {{servers}}.',
  fileAllocation: 'File allocation error. Allocated {{actualSize}} out of {{targetSize}}.',
  letsEncryptNotReachable: 'Connecting to Let\'s Encrypt server failed.',
  letsEncryptResponse: 'Bad Let\'s Encrypt response: {{errorMessage}}.',
  nodeAlreadyInCluster: 'Cannot add "{{hostname}}", it is already part of a cluster.',
  nodeNotCompatible: 'Cannot add "{{hostname}}", it is a {{clusterType}} node.',
  noConnectionToNewNode: 'Cannot add node "{{hostname}}", connection failed.',
  noServiceNodes: 'Service {{service}} is not deployed on any node.',
  userNotInCluster: 'Authenticated user is not a member of this cluster.',

  // Unexpected error
  unexpectedError: 'Unexpected error, reference: {{reference}}.',

  translationParts: {
    inviteToken: 'invite token',
    accessToken: 'access token',
    identityToken: 'identity token',
    storageTestOperations: {
      read: 'read',
      write: 'write',
      remove: 'remove',
    },
    nodeServices: {
      couchbase: 'Database',
      cluster_manager: 'Cluster Manager',
      cluster_worker: 'Cluster Worker',
      letsencrypt: 'Let\'s Encrypt',
      oneprovider: 'Oneprovider',
      op_worker: 'Oneprovider Worker',
      onezone: 'Onezone',
      oz_worker: 'Onezone Worker',
    },
    posixErrno: {
      eperm: 'Operation not permitted',
      enoent: 'No such file or directory',
      esrch: 'No such process',
      eintr: 'Interrupted system call',
      eio: 'I/O error',
      enxio: 'No such device or address',
      e2big: 'Arg list too long',
      enoexec: 'Exec format error',
      ebadf: 'Bad file number',
      echild: 'No children',
      eagain: 'Temporary failure',
      enomem: 'Not enough core',
      eacces: 'Permission denied',
      efault: 'Bad address',
      enotblk: 'Block device required',
      ebusy: 'Mount device busy',
      eexist: 'File exists',
      exdev: 'Cross-device link',
      enodev: 'No such device',
      enotdir: 'Not a directory',
      eisdir: 'Is a directory',
      einval: 'Invalid argument',
      enfile: 'Too many open files in system',
      emfile: 'Too many open files',
      enotty: 'Not a typewriter',
      etxtbsy: 'Text file busy',
      efbig: 'File too large',
      enospc: 'No space left on device',
      espipe: 'Illegal seek',
      erofs: 'Read only file system',
      emlink: 'Too many links',
      epipe: 'Broken pipe',
      edom: 'Math arg out of domain of func',
      erange: 'Math result not representable',
      enomsg: 'No message of desired type',
      eidrm: 'Identifier removed',
      echrng: 'Channel number out of range',
      el2nsync: 'Level 2 not synchronized',
      el3hlt: 'Level 3 halted',
      el3rst: 'Level 3 reset',
      elnrng: 'Link number out of range',
      eunatch: 'Protocol driver not attached',
      enocsi: 'No CSI structure available',
      el2hlt: 'Level 2 halted',
      edeadlk: 'Deadlock condition',
      enolck: 'No record locks available',
      ebade: 'Invalid exchange',
      ebadr: 'Invalid request descriptor',
      exfull: 'Exchange full',
      enoano: 'No anode',
      ebadrqc: 'Invalid request code',
      ebadslt: 'Invalid slot',
      edeadlock: 'File locking deadlock error',
      ebfont: 'Bad font file fmt',
      enostr: 'Device not a stream',
      enodata: 'No data (for no delay io)',
      etime: 'Timer expired',
      enosr: 'Out of streams resources',
      enonet: 'Machine is not on the network',
      enopkg: 'Package not installed',
      eremote: 'The object is remote',
      enolink: 'The link has been severed',
      eadv: 'Advertise error',
      esrmnt: 'Srmount error',
      ecomm: 'Communication error on send',
      eproto: 'Protocol error',
      emultihop: 'Multihop attempted',
      elbin: 'Inode is remote (not really error)',
      edotdot: 'Cross mount point (not really error)',
      ebadmsg: 'Trying to read unreadable message',
      eftype: 'Inappropriate file type or format',
      enotuniq: 'Given log. name not unique',
      ebadfd: 'f.d. invalid for this operation',
      eremchg: 'Remote address changed',
      elibacc: 'Can \'t access a needed shared lib ',
      elibbad: 'Accessing a corrupted shared lib',
      elibscn: '.lib section in a.out corrupted',
      elibmax: 'Attempting to link in too many libs',
      elibexec: 'Attempting to exec a shared library',
      enosys: 'Function not implemented',
      enmfile: 'No more files',
      enotempty: 'Directory not empty',
      enametoolong: 'File or path name too long',
      eloop: 'Too many symbolic links',
      eopnotsupp: 'Operation not supported on transport endpoint',
      epfnosupport: 'Protocol family not supported',
      econnreset: 'Connection reset by peer',
      enobufs: 'No buffer space available',
      eafnosupport: 'Address family not supported by protocol family',
      eprototype: 'Protocol wrong type for socket',
      enotsock: 'Socket operation on non-socket',
      enoprotoopt: 'Protocol not available',
      eshutdown: 'Can \'t send after socket shutdown ',
      econnrefused: 'Connection refused',
      eaddrinuse: 'Address already in use',
      econnaborted: 'Connection aborted',
      enetunreach: 'Network is unreachable',
      enetdown: 'Network interface is not configured',
      etimedout: 'Connection timed out',
      ehostdown: 'Host is down',
      ehostunreach: 'Host is unreachable',
      einprogress: 'Connection already in progress',
      ealready: 'Socket already connected',
      edestaddrreq: 'Destination address required',
      emsgsize: 'Message too long',
      eprotonosupport: 'Unknown protocol',
      esocktnosupport: 'Socket type not supported',
      eaddrnotavail: 'Address not available',
      eisconn: 'Socket is already connected',
      enotconn: 'Socket is not connected',
      enotsup: 'Not supported',
      enomedium: 'No medium (in tape drive)',
      enoshare: 'No such host or network path',
      ecaseclash: 'Filename exists with different case',
      eoverflow: 'Value too large for defined data type',
    },
    caveatErrors: {
      time: 'Provided token has expired at {{expiredTime}}.',
      ip: 'Provided token can only be used from an IP address that matches: {{ips}}.',
      asn: 'Provided token can only be used from an IP address that maps to the following Autonomous System Number: {{asns}}.',
      geocountry: 'Provided token can only be used from an IP address that {{inclusionType}} from the following country: {{countries}}.',
      georegion: 'Provided token can only be used from an IP address that {{inclusionType}} from the following region: {{regions}}.',
      consumer: 'The consumer of provided token must authenticate {{consumers}}.',
      inclusionTypes: {
        whitelist: 'comes',
        blacklist: 'does <strong>not</strong> come',
      },
      any: 'any',
      or: 'or',
      idsLabel: {
        user: 'as one of users (id): ',
        group: 'as one of groups (id): ',
        provider: 'as one of providers (id): ',
      },
      otherCaveat: 'Provided token is not valid – unverified {{caveat.type}} caveat. More details below.',
    },
    whenReportingUseReference: 'When reporting this error, cite the following reference: "{{reference}}".',
  },
};
